function keyFor(word: string): string {
  return word
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

const USAGE_BY_WORD: Record<string, string> = {
  sartorial: 'Use it for tailoring, crisp collars, and outfits where the cut is doing the talking.',
  sprezzatura: 'Wear it when the look feels effortless, but the proportions are quietly controlled.',
  insouciant: 'Use it for undone polish: a relaxed shirt, easy trouser, and no visible panic.',
  louche: 'Save it for rakish evening pieces, soft tailoring, and one slightly dangerous detail.',
  elan: 'Use it when the outfit needs movement, confidence, and a little theatrical speed.',
  panache: 'Wear it as one decisive flourish: bright scarf, sharp shoe, or dramatic sleeve.',
  diaphanous: 'Use it for sheer layers, gauzy dresses, and warm days that still need romance.',
  bespoke: 'Apply it when fit matters most: waist, shoulder, sleeve, and hem all considered.',
  nonchalant: 'Wear it with relaxed structure: the outfit looks easy because the edit is strict.',
  raffish: 'Use it for a charmingly imperfect detail: rumpled linen, worn leather, or open collar.',
  opulent: 'Wear it through texture before logos: velvet, satin, heavy knit, or polished metal.',
  austere: 'Use it when restraint is the point: spare shapes, quiet colour, and clean edges.',
  languid: 'Wear it with drape, soft volume, and pieces that move slowly around the body.',
  silhouette: 'Use it to check the outline first: long over short, wide over slim, or clean column.',
  atelier: 'Apply it to details that feel made, not bought: seam, fold, stitch, and finish.',
  couture: 'Use it sparingly for high-effort construction: sculpted shapes and precise drama.',
  toile: 'Think of it as a test run: try the proportion before committing to the full look.',
  maison: 'Use it when the outfit feels like a whole house style, not five unrelated pieces.',
  'pret-a-porter': 'Use it for polished ready-to-wear ease: styled, practical, and out the door.',
  gestalt: 'Check whether the full look coheres before obsessing over any single piece.',
  zeitgeist: 'Use it when the outfit catches the current mood without becoming a costume.',
  demode: 'Use it as a warning: dated is fine only when the styling makes it intentional.',
  'avant-garde': 'Wear it when one experimental proportion is enough; let the rest stay grounded.',
  ecru: 'Use it as a softer neutral than white, especially with denim, camel, black, or navy.',
  celadon: 'Wear it as a quiet colour lift with cream, grey, chocolate, or deep blue.',
  mauve: 'Use it when pink feels too sweet and purple feels too loud.',
  umber: 'Wear it as an earthy anchor for cream, rust, denim, or black.',
  tawny: 'Use it for warm leather, suede, and autumn-toned layers.',
  alabaster: 'Wear it when white needs to feel softer, smoother, and more expensive.',
  burnished: 'Use it for accessories with glow: aged gold, polished leather, or warm hardware.',
  capsule: 'Use it when every piece has to earn repeat wear.',
  curation: 'Treat the outfit like an edit: remove the piece that says the least.',
  provenance: 'Wear the piece with a story when the rest of the look is restrained enough to hear it.',
  archive: 'Use it for vintage, saved favourites, and pieces that look better with history.',
  monochromatic: 'Wear one colour family and let texture create the contrast.',
  sculptural: 'Use it when shape matters more than print: strong shoulder, curved hem, clean volume.',
  deconstructed: 'Wear it when asymmetry, raw edges, or exposed structure feel deliberate.',
  understated: 'Use it when the flex is fit, fabric, and restraint.',
  draped: 'Wear it with fluid fabric and keep shoes or accessories sharper for balance.',
  cinched: 'Use it when volume needs a waist, belt, tie, or gathered point.',
  oversized: 'Wear one oversized piece at a time unless the whole silhouette is intentional.',
  textural: 'Use it when colour is quiet but the outfit still needs depth.',
  polished: 'Use it when the outfit needs a finished edge: pressed, clean, and intentional.',
  heritage: 'Wear it through classic fabrics: wool, tweed, trench cloth, denim, or leather.',
  gilded: 'Use it for a controlled gleam, not head-to-toe shine.',
  chromatic: 'Wear it when colour is the strategy, not the accident.',
  studied: 'Use it when the outfit looks simple but every proportion has been selected.',
  verdant: 'Wear it through fresh greens, botanical prints, or a single lively accent.',
  slouchy: 'Balance it with one clean line so relaxed does not become collapsed.',
  laconic: 'Use it for minimal outfits that communicate through precision, not decoration.',
  palette: 'Choose the colour story first, then let pieces audition against it.',
  'je ne sais quoi': 'Use it when the exact reason is hard to name, but the styling feels alive.',
  'jolie laide': 'Wear the odd piece on purpose; beauty gets more interesting with tension.',
  ennui: 'Use it for moody restraint: black, grey, soft tailoring, and world-weary elegance.',
  chic: 'Use it only when the edit is clean enough that nothing needs explaining.',
  proportion: 'Check lengths, widths, and balance before changing colours.',
  craft: 'Use it when construction, texture, or hand-finished detail is the point.',
  wardrobe: 'Think beyond one outfit: will this piece work with the rest of your life?',
  minimal: 'Use fewer pieces, but make the shape and fabric carry more weight.',
  cobalt: 'Wear it as a decisive blue accent against black, white, grey, or camel.',
  eclecticism: 'Mix references, but repeat one colour or shape so the look has discipline.',
};

export function fashionUsageFor(word: string): string {
  return USAGE_BY_WORD[keyFor(word)] ?? 'Use it as a styling prompt: pick one piece that makes the word visible.';
}
